# Generated by Django 3.0 on 2026-01-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='demo',
        ),
    ]
