# Generated by Django 3.0 on 2026-01-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20260104_0323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demo',
            new_name='Task',
        ),
    ]
